name: Deploy le-commandHeure

on:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH KEY
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSSHKEY }}
        know_host: 'just-a-placeholder'
      - name: Adding Know host
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/know_host
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{secrets.SSSHKEY}}@${{secrets.HOST}}:/var/www/le-commandHeure
